management:
  security:
    enabled: false

logging:
  level:
    root: WARN
    com:
      orangeandbronze: DEBUG
feign:
  hystrix:
    enabled:
       true
hystrix:
  command:
    default:
      execution:
        isolation:
           strategy: SEMAPHORE
